version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    volumes:
     - /tmp:/usr/share/elasticsearch/data
#     - /tmp/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#     - /tmp:/var/lib/elasticsearch/data
#     - /tmp:/var/log/elasticsearch
    ports:
     - 9200:9200
     - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    ports:
     - 5601:5601
  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.3
  filebeat:
    image: docker.elastic.co/beats/filebeat:5.6.3
    volumes:
      - /tmp/filebeat.yml:/usr/share/filebeat/filebeat.yml
#      - /tmp/filebeat.yml:/usr/share/filebeat/filebeat.yml
